version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  taiga_backend_media: {}

services:
  postgresql:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      - POSTGRES_USER=taiga
      - POSTGRES_DB=taiga
      - POSTGRES_PASSWORD=123

  redis:
    image: redis:4.0-alpine

  rabbitmq:
    image: rabbitmq:3.6-alpine
    hostname: taiga_rabbitmq
    environment:
      # https://www.rabbitmq.com/clustering.html#erlang-cookie
      - RABBITMQ_ERLANG_COOKIE='secret_cookie_here'
      - RABBITMQ_DEFAULT_USER=taiga
      - RABBITMQ_DEFAULT_PASS=taiga
      - RABBITMQ_DEFAULT_VHOST=taiga
      # http://www.rabbitmq.com/configure.html#config-items
      # - RABBITMQ_HIPE_COMPILE=1

  backend:
    # build: backend/
    image: dougg/taiga-backend
    volumes:
      - taiga_backend_media:/taiga_backend/media
      - /taiga_backend/static-root
    environment:
      - DJANGO_DEBUG=true
      - DJANGO_SECRET_KEY=DJANGO_SECRET_KEY
      - DJANGO_DB_USER=taiga
      - DJANGO_DB_NAME=taiga
      - DJANGO_DB_PASSWORD=123
      - DJANGO_DB_HOST=postgresql

      - USE_GITLAB=${USE_GITLAB}
      - GITLAB_URL=${GITLAB_URL}
      - GITLAB_CLIENT_ID=${GITLAB_CLIENT_ID}
      - GITLAB_SECRET=${GITLAB_SECRET}

      - DJANGO_ALLOWED_HOSTS=${HOSTNAME}
      - TAIGA_PUBLIC_REGISTER_ENABLED=${PUBLIC_REGISTER_ENABLED}
      - TAIGA_SSL=false

      - USE_ANYMAIL=false
      - ANYMAIL_MAILGUN_API_KEY=MAILGUN-KEY
      - DJANGO_DEFAULT_FROM_EMAIL=example@example.com

    user: taiga
    entrypoint: ['/scripts/entrypoint.sh']
    # command: ['gunicorn', '--worker-class', 'gevent', '--workers', '10', '-b', '0.0.0.0:8000', 'taiga.wsgi']
    command: ['gunicorn', '-b', '0.0.0.0:8000', 'taiga.wsgi']

  celeryworker:
    extends: backend
    entrypoint: []
    command: ['celery', '-A', 'taiga', 'worker', '-P', 'gevent', '-c', '4', '--loglevel', 'debug']
    depends_on:
      - redis
      - rabbitmq

  frontend:
    # build: frontend
    image: dougg/taiga-frontend
    volumes_from:
      - backend:ro
    environment:
       - TAIGA_DEBUG=true
       - TAIGA_API_URL=${WEB_PROTOCOL}://${HOSTNAME}/api/v1/
       - TAIGA_EVENTS_URL=${WEBSOCKET_PROTOCOL}://${HOSTNAME}/events
       - TAIGA_PUBLIC_REGISTER_ENABLED=${PUBLIC_REGISTER_ENABLED}
       - DEFAULT_LANGUAGE=en
       - USE_GITLAB=${USE_GITLAB}
       - GITLAB_URL=${GITLAB_URL}
       - GITLAB_CLIENT_ID=${GITLAB_CLIENT_ID}
    ports:
      - "80:80"
    depends_on:
      - postgresql
      - backend
      - events

  events:
    # build: events/
    image: dougg/taiga-events
    environment:
      - TAIGA_SECRET=DJANGO_SECRET_KEY
    depends_on:
      - rabbitmq
